language: node_js
node_js:
  - "14"
services:
  - docker
branches:
  only:
    - master

before_install:
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t bikachaosky/project-convertible-bond:latest .
  - docker push bikachaosky/project-convertible-bond:latest